#!/usr/bin/env ruby

require 'pathname'
require 'securerandom'
require 'yaml'

config_dir = Pathname.new File.join __dir__, '..', 'config'
secrets_path = config_dir.join 'secrets.yml'
if secrets_path.exist?
  exit 0
end

envs = Dir.glob("#{config_dir}/environments/*.rb").map { |f| File.basename(f).gsub(/\.rb$/, '') }

secrets = {}

envs.each do |env|
  secrets[env] = {}
  secrets[env]['secret_key_base'] = SecureRandom.base64(96)
  secrets[env]['db_sc'] = SecureRandom.base64(96)
end

secrets_path.open('w') do |f|
  f.write secrets.to_yaml
end
